# Generated by Django 2.2.16 on 2022-05-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220514_1908'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='уникальные подписки',
        ),
    ]
